# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.push_apk:loader

transforms:
    - taskgraph.transforms.push_apk:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - build-signing
    - push-apk-checks

job-defaults:
    description: Publishes APK onto Google Play Store
    attributes:
        nightly: true
    shipping-phase: ship
    shipping-product: fennec
    worker-type:
        by-release-level:
            production: scriptworker-k8s/gecko-3-pushapk
            staging: scriptworker-k8s/gecko-1-pushapk
    worker:
        upstream-artifacts:  # see transforms
        implementation: push-apk
        commit:
            by-release-level:
                production: true
                staging: false
    scopes:  # see transforms
    treeherder:
        platform: Android/opt
        tier: 2
        kind: other
    run-on-projects: ['try', 'mozilla-esr68']

jobs:
    push-apk-nightly/opt:
        attributes:
            release-type: nightly
        worker:
            google-play-track:
                by-release-level:
                    # See https://github.com/mozilla-releng/pushapkscript#aurora-beta-release-vs-alpha-beta-production
                    production: beta
                    staging: alpha
        treeherder:
            symbol: pub(gp-n)

    push-apk-beta/opt:
        attributes:
            release-type: beta
        worker:
            google-play-track:
                by-release-level:
                    production: production
                    staging: alpha
            rollout-percentage:
                by-release-level:
                    # XXX Change this value if google-play-track becomes rollout
                    production: null
                    staging: null
        treeherder:
            symbol: pub(gp-b)

    push-apk-release/opt:
        attributes:
            release-type: release
        worker:
            google-play-track:
                by-release-level:
                    production: rollout
                    staging: alpha
            rollout-percentage:
                by-release-level:
                    # XXX Change this value if google-play-track becomes rollout
                    production:
                        by-release-type:
                            esr68-rc: 5
                            default: 10
                    staging: null
        treeherder:
            symbol: pub(gp-r)
