# This Source Code Form is subject to the terms of the Mozilla Public
# License, v. 2.0. If a copy of the MPL was not distributed with this
# file, You can obtain one at http://mozilla.org/MPL/2.0/.
---
loader: taskgraph.loader.push_apk:loader

transforms:
    - taskgraph.transforms.push_apk_checks:transforms
    - taskgraph.transforms.task:transforms

kind-dependencies:
    - build-signing

job-defaults:
    attributes:
        nightly: true
    shipping-phase: promote
    shipping-product: fennec
    worker-type: b-linux
    worker:
        implementation: docker-worker
        os: linux
        docker-image: {in-tree: mozapkpublisher}
        chain-of-trust: true
        max-run-time: 600
    treeherder:
        platform: Android/opt
        tier: 1
        kind: test
    run-on-projects: ['try', 'mozilla-esr68']

jobs:
    push-apk-checks-nightly/opt:
        description: Verify Nightly APKs are sane before uploading them onto Google Play Store
        attributes:
            release-type: nightly
        package-name: org.mozilla.fennec_aurora
        treeherder:
            symbol: pub(gpc-n)

    push-apk-checks-beta/opt:
        description: Verify Beta APKs are sane before uploading them onto Google Play Store
        attributes:
            release-type: beta
        package-name: org.mozilla.firefox_beta
        treeherder:
            symbol: pub(gpc-b)

    push-apk-checks-release/opt:
        description: Verify Release APKs are sane before uploading them onto Google Play Store
        attributes:
            release-type: release
        package-name: org.mozilla.firefox
        treeherder:
            symbol: pub(gpc-r)
